// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnPlanUpdateOperation } from "./TurnPlanUpdateOperation";

export type TurnPlanUpdateParams = { threadId: string, expectedTurnId: string, operations: Array<TurnPlanUpdateOperation>, explanation?: string | null, };
